#############################################
###                                       ###
###             网关模块-dev               ###
###                                       ###
#############################################
server:
  port: 8880
spring:
  redis:
    database: 5
    host: localhost
    password: 123
    port: 6379
  datasource:
    druid:
      url: jdbc:mysql://wstom.cn:3306/db_novel?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: wstom
      password: wstom@dev
      #filters: config
