#############################################
###                                       ###
###             网关模块-dev               ###
###                                       ###
#############################################
server:
  port: 8080
spring:
  profiles:
    include:
  redis:
    database: 5
    host: localhost
    password: 123
    port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      # 主库数据源
      url: jdbc:mysql://wstom.cn:3306/db_wstom_novel?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: wstom
      password: wstom@dev
      # 初始连接数
      initial-size: 10
      # 最大连接池数量
      max-active: 100
      # 最小连接池数量
      min-idle: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      #打开PSCache，并且指定每个连接上PSCache的大小,
      #如果用Oracle，则把poolPreparedStatements配置为true，
      #mysql可以配置为false。分库分表较多的数据库，建议配置为false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒,
      #有两个含义：
      #1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接;
      #2) testWhileIdle的判断依据
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，
      #如果空闲时间大于timeBetweenEvictionRunsMillis，
      #执行validationQuery检测连接是否有效
      test-while-idle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /monitor/druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
mybatis-plus:
  type-aliases-package: cn.wstom.gateway
  mapper-locations: classpath:mapper/**/*Mapper.xml
  configuration:
    # 生产环境开启
    cache-enabled: false
    default-executor-type: reuse
zuul:
  host:
    connect-timeout-millis: 1800000
#  routes:
#    wstom-web:
#      path: /user/**
#      service-id: wstom-web
#      strip-prefix: true
security:
  ignored: /favicon.ico,/scripts/**,/styles/**,/images/**,/webjars/**
  sessions: ALWAYS
  oauth2:
    client:
      clientId: ssoclient
      clientSecret: ssosecret
      accessTokenUri: http://localhost:8996/oauth/token
      userAuthorizationUri: http://localhost:8996/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      jwt:
        keyUri: http://localhost:8996/oauth/token_key
wstom:
  server:
    security:
      config:
        denied-page: /deny
        permit-url:
          - /open/api
#        open-url:
        logout-success-url: /handle/logout